apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cricketerdocker-deployement
  labels:
    app: cricketerdocker
spec:
  selector: 
    matchLabels: 
      app: cricketerdocker
  replicas: 3
  template: 
    metadata: 
      labels: 
        app: cricketerdocker
    spec:
      containers: 
        - name: cricketerdocker
          image: cricketerdocker:1.0
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 8082 